### ISSUE TITLE
ConsumerStartPosition.PRODUCER not handled properly in Consumer

### ISSUE THREAD

**Issue by myNameIsPatrick** [astronomy-commons/genesis-client#41]
I was testing out this option for the Consumer and it doesn't seem to be handled properly in the Consumer:

```
  File "/home/patrick/workspace/venv/hop/lib/python3.8/site-packages/hop/subscribe.py", line 55, in _main
    with stream.open(args.url, "r") as s:
  File "/usr/lib64/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/patrick/workspace/venv/hop/lib/python3.8/site-packages/hop/io.py", line 229, in _open_consumer
    client.subscribe(t)
  File "/home/patrick/workspace/venv/hop/lib/python3.8/site-packages/adc/consumer.py", line 64, in subscribe
    tp.offset = self.conf.start_at
TypeError: an integer is required (got type ConsumerStartPosition)
```

There should be another switch in the conditional here, and possibly also in the configuration at the bottom of `consumer.py`: https://github.com/astronomy-commons/adc-streaming/blob/master/adc/consumer.py#L48

I think I'm unclear on what `ConsumerStartPosition.PRODUCER` is supposed to represent though, is this intended to be `OFFSET_STORED` or something else?

**Comment by spenczar** [comment]
I think my intention was for this to be "obey whatever the Producer set as the default for the topic when the topic was created." For some reason, I thought that `auto.offset.reset` could be an option defined for a particular topic. I think I was wrong about that. I think this value is meaningless and should be removed.

**Comment by myNameIsPatrick** [comment]
How about replacing this option with `ConsumerStartPosition.STORED` pointed towards `OFFSET_STORED` to allow starting where you left off with a given group id?

**Comment by spenczar** [comment]
I don't think we should have a `STORED` value. `ConsumerStartPosition` should, I think, represent where you start if you've never committed your position. That's what [this comment](https://github.com/astronomy-commons/adc-streaming/blob/master/adc/consumer.py#L204-L212) says, anyway. We should always obey a stored offset (but, of course, we don't actually do that, as [this FIXME](https://github.com/astronomy-commons/adc-streaming/blob/master/adc/consumer.py#L47) says).

I think I'd prefer to fix things so that stored offsets get obeyed no matter what, and leave this down to just EARLIEST/LATEST.

**Comment by myNameIsPatrick** [comment]
Oh I see, I misinterpreted what `ConsumerStartPosition` was really doing and that makes sense.

> I think I'd prefer to fix things so that stored offsets get obeyed no matter what, and leave this down to just EARLIEST/LATEST.

That sounds like a good plan.
